version: '3.3'
services:
  algorithm-mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33060:3306
    volumes:
      - "algorithm-mysql:/var/lib/mysql"
    env_file:
      - mysql.env
    networks:
      - backend

  algorithm-inference-api:
    build: ./algorithm_framework
    ports:
      - 8090:8080
    depends_on:
      - algorithm-mysql
    networks:
      - backend

volumes:
  algorithm-mysql:

networks:
  backend:
    driver: "bridge"
